language: php
php:
  - 7.0
  - 8.0

before_script:
  composer update

script: 
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml tests/
  
after_success:
  - travis_retry php vendor/bin/php-coveralls -v
